# Live: https://howardtreepros-1.onrender.com
services:
  - type: web
    name: howardtreepros-1
    runtime: docker
    plan: free
    branch: main
    autoDeployTrigger: commit
    healthCheckPath: /
